// Generated by tools/extract_panel_layout.py from the CHOMPI board files. Don't edit.
//
// The CHOMPI top panel in millimetres: the origin is the top-left corner of the outline
// and y points down. Circles are {x, y, diameter} and rectangles {x, y, width, height}.
#pragma once

namespace champi::layout
{
struct Point
{
    float x, y;
};
struct Circle
{
    float x, y, d;
};
struct Rect
{
    float x, y, w, h;
};

constexpr float kWidth  = 326.0f;
constexpr float kHeight = 106.0f;

// KEYn's switch centre is kKey[n - 1].
constexpr Point kKey[28] = {
    {22.217f, 83.502f}, {42.328f, 83.502f}, {62.439f, 83.502f},
    {82.55f, 83.502f}, {102.661f, 83.502f}, {122.773f, 83.502f},
    {142.884f, 83.502f}, {162.995f, 83.502f}, {183.106f, 83.502f},
    {203.217f, 83.502f}, {223.328f, 83.502f}, {243.439f, 83.502f},
    {263.551f, 83.502f}, {283.662f, 83.502f}, {303.773f, 83.502f},
    {32.267f, 63.502f}, {52.378f, 63.502f}, {92.601f, 63.502f},
    {112.712f, 63.502f}, {132.823f, 63.502f}, {173.045f, 63.502f},
    {193.156f, 63.502f}, {233.379f, 63.502f}, {253.49f, 63.502f},
    {273.601f, 63.502f}, {42.345f, 34.142f}, {243.456f, 34.142f},
    {263.568f, 34.142f},
};

// The LED under KEYn's cap, for KEY1-25.
constexpr Point kKeyLed[25] = {
    {22.217f, 78.452f}, {42.328f, 78.452f}, {62.439f, 78.452f},
    {82.55f, 78.452f}, {102.661f, 78.452f}, {122.773f, 78.452f},
    {142.884f, 78.452f}, {162.995f, 78.452f}, {183.106f, 78.452f},
    {203.217f, 78.452f}, {223.328f, 78.452f}, {243.439f, 78.452f},
    {263.551f, 78.452f}, {283.662f, 78.452f}, {303.773f, 78.452f},
    {32.267f, 58.452f}, {52.378f, 58.452f}, {92.601f, 58.452f},
    {112.712f, 58.452f}, {132.823f, 58.452f}, {173.045f, 58.452f},
    {193.156f, 58.452f}, {233.379f, 58.452f}, {253.49f, 58.452f},
    {273.601f, 58.452f},
};

// The LED windows over KEY26-28 (CHOMPI, play and loop).
constexpr Circle kKeyLedWindow[3] = {
    {42.356f, 13.304f, 8.4f},
    {243.467f, 10.994f, 5.1f},
    {263.578f, 10.994f, 5.1f},
};

// ENCn's shaft hole is kEncoder[n - 1]; ENC5's is the scrub wheel's.
constexpr Circle kEncoder[6] = {
    {106.0f, 34.14f, 7.7f},
    {139.555f, 34.14f, 7.7f},
    {173.073f, 34.14f, 7.7f},
    {72.5f, 34.15f, 7.7f},
    {213.295f, 34.14f, 35.5f},
    {303.784f, 34.14f, 7.7f},
};

// ENCn's LED window; ENC5 has a second one.
constexpr Circle kEncoderLedWindow[6] = {
    {106.036f, 13.304f, 8.4f},
    {139.555f, 13.304f, 8.4f},
    {173.073f, 13.304f, 8.4f},
    {72.518f, 13.304f, 8.4f},
    {203.245f, 10.994f, 5.1f},
    {303.783f, 13.304f, 8.4f},
};
constexpr Circle kEncoder5SecondLedWindow = {223.356f, 10.994f, 5.1f};

// The line-in and headphone jacks, on the right-hand side of the case.
constexpr Point kLineInJack = {316.885f, 42.393f};
constexpr Point kPhonesJack = {316.885f, 63.893f};

// The USB-C socket and the micro-SD slot, on the front edge (y past kHeight: they stick out).
constexpr Point kUsbSocket = {25.562f, 107.504f};
constexpr Point kSdSlot    = {253.527f, 110.871f};

// The cut-out the white and black rows show through, corner by corner.
constexpr Point kKeyboardCutout[40] = {
    {22.0f, 54.0f}, {22.5f, 53.5f}, {62.15f, 53.5f}, {62.65f, 54.0f},
    {62.65f, 73.0f}, {63.15f, 73.55f}, {81.85f, 73.55f}, {82.35f, 73.05f},
    {82.35f, 54.0f}, {82.85f, 53.5f}, {142.6f, 53.5f}, {143.1f, 54.0f},
    {143.1f, 73.0f}, {143.6f, 73.5f}, {162.3f, 73.5f}, {162.8f, 73.0f},
    {162.8f, 54.0f}, {163.3f, 53.5f}, {202.9f, 53.5f}, {203.4f, 54.0f},
    {203.4f, 73.0f}, {203.9f, 73.5f}, {222.6f, 73.5f}, {223.1f, 73.0f},
    {223.1f, 54.0f}, {223.6f, 53.5f}, {283.35f, 53.5f}, {283.85f, 54.0f},
    {283.85f, 73.0f}, {284.4f, 73.5f}, {313.55f, 73.5f}, {314.05f, 74.0f},
    {314.05f, 93.55f}, {313.55f, 94.05f}, {12.45f, 94.05f}, {11.95f, 93.55f},
    {11.95f, 74.0f}, {12.45f, 73.5f}, {21.5f, 73.5f}, {22.0f, 73.0f},
};
constexpr Rect kChompiCutout   = {32.05f, 24.15f, 20.6f, 20.55f};
constexpr Rect kPlayLoopCutout = {233.15f, 24.25f, 40.65f, 20.5f};
constexpr Rect kToggleSlot     = {19.25f, 30.65f, 5.0f, 7.5f};

// The mic's sound slots.
constexpr Rect kMicSlots[5] = {
    {281.27f, 11.5f, 1.24f, 3.56f},
    {283.418f, 9.5f, 1.24f, 7.56f},
    {285.66f, 8.215f, 1.244f, 10.1f},
    {287.91f, 9.5f, 1.24f, 7.56f},
    {290.08f, 11.51f, 1.24f, 3.56f},
};

} // namespace champi::layout
